{
 "title": "Grafana Dashboards Updater",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Status of dashboard sync [1m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(grafana_dashboards_syncer_dashboard_updated[1m])",
     "legendFormat": "updated"
    },
    {
     "expr": "increase(grafana_dashboards_syncer_dashboard_not_updated[1m])",
     "legendFormat": "not updated"
    }
   ]
  },
  {
   "title": "Modifications of dashboard directory [1m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "increase(grafana_dashboards_syncer_dashboard_directory_save[1m])",
     "legendFormat": "save"
    },
    {
     "expr": "increase(grafana_dashboards_syncer_dashboard_directory_remove[1m])",
     "legendFormat": "remove"
    }
   ]
  },
  {
   "title": "Status of dashboard downloading [1m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "increase(grafana_dashboards_syncer_download_success[1m])",
     "legendFormat": "{{dashboard}} success"
    },
    {
     "expr": "increase(grafana_dashboards_syncer_download_failure[1m])",
     "legendFormat": "{{dashboard}} failure"
    }
   ]
  },
  {
   "title": "Listing dashboard directory [1m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "increase(grafana_dashboards_syncer_dashboard_directory_list_from_cache[1m])",
     "legendFormat": "source: cache"
    },
    {
     "expr": "increase(grafana_dashboards_syncer_dashboard_directory_list_from_drive[1m])",
     "legendFormat": "source: cache"
    }
   ]
  }
 ]
}